// <auto-generated />
using System;
using GuestManagement.Infrastructure.Guests;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GuestManagement.Infrastructure.Migrations
{
    [DbContext(typeof(GuestDbContext))]
    [Migration("20220201081910_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GuestManagement.Domain.Guests.Guest", b =>
                {
                    b.Property<string>("GuestId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("Email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FirstName")
                        .HasColumnName("FirstName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("LastName")
                        .HasColumnName("LastName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnName("PhoneNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("GuestId");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("GuestManagement.Domain.Guests.Visits.Visit", b =>
                {
                    b.Property<int>("VisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("GuestId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<bool>("IsActive")
                        .HasColumnName("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Paycheck")
                        .HasColumnName("Paycheck")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("TimeEnd")
                        .HasColumnName("TimeEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("TimeStart")
                        .HasColumnName("TimeStart")
                        .HasColumnType("datetime(6)");

                    b.HasKey("VisitId");

                    b.HasIndex("GuestId");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("GuestManagement.Domain.Guests.Visits.Visit", b =>
                {
                    b.HasOne("GuestManagement.Domain.Guests.Guest", null)
                        .WithMany("Visits")
                        .HasForeignKey("GuestId");
                });
#pragma warning restore 612, 618
        }
    }
}
